# Generated by Django 3.1.3 on 2020-11-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
